### 회원 저장
POST localhost:8080/account/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "securePassword123",
  "role": "MEMBER",
  "username": "user123"
}

### 회원 저장
POST localhost:8080/account/register
Content-Type: application/json

{
  "email": "fda@gmail.com",
  "password": "fdsfdsa",
  "role": "MEMBER",
  "username": "fda"
}